services:
  react-app-prod:
    container_name: react-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:80